#!/bin/bash
# Fetch Median XL SpeedcalcData.txt and regenerate speedcalcData.au3.
# Run from the repo root when MXL animation data changes, then recompile.
# On Windows use Git Bash. D2Stats.exe does not download this file.
set -euo pipefail

cd "$(dirname "$0")"

URL="https://dev.median-xl.com/speedcalc/SpeedcalcData.txt"
OUT="speedcalcData.au3"
DATE=$(date +"%Y-%m-%d")

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

curl -fsSL "$URL" -o "$TMP"

header=$(head -n 1 "$TMP" | tr -d '\r')
if [ "$header" != "CofName	FramesPerDirection	AnimationSpeed" ]; then
	echo "update-speedcalc-data.sh: unexpected header: $header" >&2
	exit 1
fi

rows=$(awk -F '\t' '
	BEGIN { RS = "\r\n|\n|\r" }
	NR > 1 && NF >= 3 && $1 != "" && $2 ~ /^[0-9]+$/ && $3 ~ /^[0-9]+$/ { c++ }
	END { print c+0 }
' "$TMP")

if [ "$rows" -lt 1 ]; then
	echo "update-speedcalc-data.sh: parsed 0 entries from $URL" >&2
	exit 1
fi

{
	echo "; Generated by update-speedcalc-data.sh"
	echo "; Source: $URL"
	echo "; Generated: $DATE ($rows entries)"
	echo ";"
	echo "; Do not edit by hand. Re-run update-speedcalc-data.sh when Median XL"
	echo "; animation data changes, then recompile D2Stats."
	echo ""
	echo "global \$g_avSpeedcalcData[][3] = [ _"
	awk -F '\t' '
		BEGIN { RS = "\r\n|\n|\r" }
		NR > 1 && NF >= 3 && $1 != "" && $2 ~ /^[0-9]+$/ && $3 ~ /^[0-9]+$/ {
			name = $1
			gsub(/"/, "", name)
			count++
			line[count] = sprintf("\t[\"%s\", %s, %s]", name, $2, $3)
		}
		END {
			for (i = 1; i <= count; i++) {
				if (i < count)
					print line[i] ", _"
				else
					print line[i] " _"
			}
		}
	' "$TMP"
	echo "]"
} > "$OUT"

echo "update-speedcalc-data.sh: wrote $rows entries to $OUT"
